---
kind: pipeline
type: kubernetes
name: default
steps:
- name: restore cache
  image: harbor.xirion.net/hub/plugins/s3-cache
  settings:
    pull: true
    endpoint: http://192.168.0.112:9000
    root: drone
    restore: true
    access_key:
      from_secret: MINIO_ACCESS_KEY
    secret_key:
      from_secret: MINIO_SECRET_KEY

- name: test
  image: harbor.xirion.net/hub/library/elixir
  commands:
    - mix local.rebar --force
    - mix local.hex --force
    - mix deps.get
    - mix test

- name: rebuild cache
  image: harbor.xirion.net/hub/plugins/s3-cache
  settings:
    pull: true
    root: drone
    endpoint: http://192.168.0.112:9000
    access_key:
      from_secret: MINIO_ACCESS_KEY
    secret_key:
      from_secret: MINIO_SECRET_KEY
    rebuild: true
    mount:
      - deps
      - _build
    when:
      event: push
- name: kaniko
  image: harbor.xirion.net/finitum/drone-kaniko:0.8.1
  when:
    branch: [main]
  settings:
    cache: true
    username:
      from_secret: REGISTRY_USER
    password:
      from_secret: REGISTRY_PASSWORD
    registry: harbor.xirion.net
    repo: library/dps   
    tags: latest

services:
- name: postgres
  image: harbor.xirion.net/hub/library/postgres:13-alpine
  environment:
    POSTGRES_DB: dps_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
